language: java

cache:
  directories:
    - $HOME/.m2/repository/backport-util-concurrent/backport-util-concurrent
    - $HOME/.m2/repository/classworlds/classworlds
    - $HOME/.m2/repository/com/beust
    - $HOME/.m2/repository/com/google
    - $HOME/.m2/repository/commons-io/commons-io
    - $HOME/.m2/repository/io/netty
    - $HOME/.m2/repository/junit/junit
    - $HOME/.m2/repository/org/apache
    - $HOME/.m2/repository/org/asciidoctor
    - $HOME/.m2/repository/org/codehaus
    - $HOME/.m2/repository/org/jruby
    - $HOME/.m2/repository/org/sonatype

install:
    # We don't have any use for the zip'd files, so stop before the package phase
    - mvn prepare-package -B

script:
    - mkdir -p aggregation/$TRAVIS_BRANCH/$TRAVIS_PULL_REQUEST
    - cp -t aggregation/$TRAVIS_BRANCH/$TRAVIS_PULL_REQUEST travis/index.html
    - for m in authorization_services getting_started securing_apps server_admin server_development server_installation; do cp -a $m/target/generated-docs aggregation/$TRAVIS_BRANCH/$TRAVIS_PULL_REQUEST/$m; done
    - travis/deploy_gh-pages.sh $TRAVIS_REPO_SLUG aggregation/
    - |-
        travis/comment_github.sh $TRAVIS_REPO_SLUG $TRAVIS_PULL_REQUEST "[Documentation](https://$(dirname $TRAVIS_REPO_SLUG).github.io/$(basename $TRAVIS_REPO_SLUG)/$TRAVIS_BRANCH/$TRAVIS_PULL_REQUEST/master.html)"
