language: java

install:
    - mvn package -B

script:
    - mkdir -p aggregation/$TRAVIS_BRANCH/$TRAVIS_PULL_REQUEST
    - cp -at aggregation/$TRAVIS_BRANCH/$TRAVIS_PULL_REQUEST server_admin/target/generated-docs/.
    - ./deploy_gh-pages.sh $TRAVIS_REPO_SLUG aggregation/
